// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb3_kOVpd7ryIUj3gy5JrzWpg7m-7Kt0Y',
    appId: '1:549319030196:web:2d564b9eac8ae526ee6ee1',
    messagingSenderId: '549319030196',
    projectId: 'noteshouse-d6b0c',
    authDomain: 'noteshouse-d6b0c.firebaseapp.com',
    storageBucket: 'noteshouse-d6b0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBibN1VE7AghIlET8r7W7J6XbpDzbtI1hI',
    appId: '1:549319030196:android:3b55ee072e45ce9bee6ee1',
    messagingSenderId: '549319030196',
    projectId: 'noteshouse-d6b0c',
    storageBucket: 'noteshouse-d6b0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSEaC_jePTMjmTz0W1jymge9rvlCmKpxY',
    appId: '1:549319030196:ios:35f2d39eb63e4af5ee6ee1',
    messagingSenderId: '549319030196',
    projectId: 'noteshouse-d6b0c',
    storageBucket: 'noteshouse-d6b0c.firebasestorage.app',
    iosBundleId: 'com.example.fypUiDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSEaC_jePTMjmTz0W1jymge9rvlCmKpxY',
    appId: '1:549319030196:ios:35f2d39eb63e4af5ee6ee1',
    messagingSenderId: '549319030196',
    projectId: 'noteshouse-d6b0c',
    storageBucket: 'noteshouse-d6b0c.firebasestorage.app',
    iosBundleId: 'com.example.fypUiDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb3_kOVpd7ryIUj3gy5JrzWpg7m-7Kt0Y',
    appId: '1:549319030196:web:8508d2895dd7539aee6ee1',
    messagingSenderId: '549319030196',
    projectId: 'noteshouse-d6b0c',
    authDomain: 'noteshouse-d6b0c.firebaseapp.com',
    storageBucket: 'noteshouse-d6b0c.firebasestorage.app',
  );

}